### ISSUE TITLE
Useful M codes

### ISSUE THREAD

**Issue by apshu** [fragmuffin/pygcode#11] opened 2017-12-11 10:12 UTC
Hi Peter,

   I like the pygcode very much. I am using your library to simulate GCode and create laser path optimization for my hobby machine. It works perfectly. 
 
   The simulation usability could be improved by adding some non LinuxCNC standard codes:

M18 (disable steppers, GCodeMovement will automatically reenable stepper)
M80 (ATX power on)
M81 (ATX power off)

If the ATX power is off, the GCode consumed will not cause any physical movement. A parameter in the Machine object reflecting the ATX power state would be useful.

The M18 is implementation specific, nevertheless a NoOP calss would be useful in the pygcode distribution eliminate ERROR on parsing.

Thanks for your time and great work done!
   Attila

**Comment by fragmuffin** [comment] 2017-12-11 14:32
Hi @apshu !
I'm so glad you like it!

> The simulation usability could be improved by adding some non LinuxCNC standard codes:

I couldn't agree more, this is the number 1 thing requested at this early stage, and has been raised in #9.

you can work around this limitation by defining your own gcodes in your script... I've just updated #9 with a workaround instruction.

If you don't mind me asking, what flavour of gcode does your hobby cnc machine take?
I've got a list of _dialects_ I want to target, if yours is a new one, I'd love to add it to the list.

I'll mark this issue as a duplicate of that one and close it, but please feel free to continue the discussion in #9 :+1: 

Also, I won't get a chance this year to do this.. I'm quite busy on another project, but I want to fix it soon.

**Closed by fragmuffin** 2017-12-11 14:32 UTC
Labels: duplicate
